//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technikmarkt
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_computer
    {
        public string c_prozessor { get; set; }
        public string c_graphikkarte { get; set; }
        public decimal c_p_gtin { get; set; }
    
        public virtual p_produkt p_produkt { get; set; }
    }
}
