//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technikmarkt
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_haendler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public h_haendler()
        {
            this.hp_haendlerkauftprodukt = new HashSet<hp_haendlerkauftprodukt>();
            this.ve_verkauftan = new HashSet<ve_verkauftan>();
            this.ve_verkauftan1 = new HashSet<ve_verkauftan>();
            this.v_verkaufsraum = new HashSet<v_verkaufsraum>();
        }
    
        public string h_haendlername { get; set; }
        public string h_haendlerwebseite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hp_haendlerkauftprodukt> hp_haendlerkauftprodukt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ve_verkauftan> ve_verkauftan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ve_verkauftan> ve_verkauftan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<v_verkaufsraum> v_verkaufsraum { get; set; }
    }
}
