//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technikmarkt
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_produkt()
        {
            this.hp_haendlerkauftprodukt = new HashSet<hp_haendlerkauftprodukt>();
        }
    
        public decimal p_gtin { get; set; }
        public string p_name { get; set; }
        public string p_a_anbietername { get; set; }
        public decimal p_speicherkapazitaetgb { get; set; }
        public decimal p_preis { get; set; }
    
        public virtual a_anbieter a_anbieter { get; set; }
        public virtual c_computer c_computer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hp_haendlerkauftprodukt> hp_haendlerkauftprodukt { get; set; }
        public virtual l_laufwerk l_laufwerk { get; set; }
        public virtual s_smartphone s_smartphone { get; set; }
    }
}
