//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technikmarkt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechnikmarktEntities : DbContext
    {
        public TechnikmarktEntities()
            : base("name=TechnikmarktEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_anbieter> a_anbieter { get; set; }
        public virtual DbSet<c_computer> c_computer { get; set; }
        public virtual DbSet<h_haendler> h_haendler { get; set; }
        public virtual DbSet<hp_haendlerkauftprodukt> hp_haendlerkauftprodukt { get; set; }
        public virtual DbSet<l_laufwerk> l_laufwerk { get; set; }
        public virtual DbSet<p_produkt> p_produkt { get; set; }
        public virtual DbSet<s_smartphone> s_smartphone { get; set; }
        public virtual DbSet<v_verkaufsraum> v_verkaufsraum { get; set; }
        public virtual DbSet<ve_verkauftan> ve_verkauftan { get; set; }
    }
}
