//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technikmarkt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ve_verkauftan
    {
        public decimal ve_gtin { get; set; }
        public string ve_h_haendlervon { get; set; }
        public string ve_h_haendleran { get; set; }
    
        public virtual h_haendler h_haendler { get; set; }
        public virtual h_haendler h_haendler1 { get; set; }
    }
}
